Categories
Oleksandr-Radovets/SecurityNew pull request #4
Opened 2024-02-22 12:21 UTC by Oleksandr-Radovets

2024-02-22 18:09 UTC, MentorMA requested changes

2024-02-22 18:09 UTC, MentorMA commented on src/main/java/com/example/securitynew/config/SecurityConfig.java
>                                  .permitAll()
Why you divide permits?

2024-02-22 18:09 UTC, MentorMA commented on src/main/java/com/example/securitynew/controller/CategoryController.java
> +    @PreAuthorize("has_Role('ROLE_ADMIN')")
Keep same style of spaces between methods

2024-02-22 18:09 UTC, MentorMA commented on src/main/java/com/example/securitynew/dto/user/UserResponseDto.java
> +
```suggestion
```

2024-02-22 18:09 UTC, MentorMA commented on src/main/java/com/example/securitynew/security/CustomUserDetails.java
> +
```suggestion
```

2024-02-22 18:09 UTC, MentorMA commented on src/main/java/com/example/securitynew/service/impl/UserServiceImpl.java
>              throw new RegistrationException("Unable to complete registration.");
Write more informative message, like "user with this email already exist" or smth else

2024-02-23 23:08 UTC, Oleksandr-Radovets commented on src/main/java/com/example/securitynew/config/SecurityConfig.java
>                                  .permitAll()
це з попереднього проекту

2024-02-23 23:09 UTC, Oleksandr-Radovets commented
не розубію що ще виправляти бо ніби все перевірив

2024-02-24 11:30 UTC, olekskov approved these changes

2024-03-08 10:27 UTC, merged